#ifndef SIMPLEDB_BTREEMETA_H
#define SIMPLEDB_BTREEMETA_H

#include <stdint.h>

#include <row.h>
#include <pager.h>

// Common Node Header Layout
enum
{
  NODE_TYPE_SIZE = sizeof(uint8_t),
  NODE_TYPE_OFFSET = 0,

  IS_ROOT_SIZE = sizeof(uint8_t),
  IS_ROOT_OFFSET = NODE_TYPE_SIZE,

  PARENT_POINTER_SIZE = sizeof(uint32_t),
  PARENT_POINTER_OFFSET = IS_ROOT_OFFSET + IS_ROOT_SIZE,

  COMMON_NODE_HEADER_SIZE = NODE_TYPE_SIZE + IS_ROOT_SIZE + PARENT_POINTER_SIZE,
};

// Leaf Node Header Layout
enum
{
  LEAF_NODE_NUM_CELLS_SIZE = sizeof(uint32_t),
  LEAF_NODE_NUM_CELLS_OFFSET = COMMON_NODE_HEADER_SIZE,

  LEAF_NODE_HEADER_SIZE = COMMON_NODE_HEADER_SIZE + LEAF_NODE_NUM_CELLS_SIZE,
};

// Leaf Node Body Layout
enum
{
  LEAF_NODE_KEY_SIZE = sizeof(uint32_t),
  LEAF_NODE_KEY_OFFSET = 0,

  LEAF_NODE_VALUE_SIZE = ROW_SIZE,
  LEAF_NODE_VALUE_OFFSET = LEAF_NODE_KEY_OFFSET + LEAF_NODE_KEY_SIZE,

  LEAF_NODE_CELL_SIZE = LEAF_NODE_KEY_SIZE + LEAF_NODE_VALUE_SIZE,
  LEAF_NODE_SPACE_FOR_CELLS = PAGE_SIZE - LEAF_NODE_HEADER_SIZE,
  LEAF_NODE_MAX_CELLS = LEAF_NODE_SPACE_FOR_CELLS / LEAF_NODE_CELL_SIZE
};

#endif
